---
- name: Copy source code
  become: no
  local_action: ansible.builtin.command rsync --exclude='.git' -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i {{workspace}}/e2essh' -aW {{ workspace }} {{ ansible_user }}@{{ inventory_hostname }}:.

- name: Create outputs dir
  ansible.builtin.file:
    path: "/home/{{ansible_user}}/e2e-testing/outputs"
    state: directory
    mode: '0755'
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
