---
- name: Create test script file
  become: no
  copy:
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: '0777'
    dest: "/home/{{ansible_user}}/e2e-testing/.ci/scripts/functional-test.sh"
    content: |
       #!/usr/bin/env bash
       set -euxo pipefail
       BASE_DIR="/home/{{ansible_user}}/e2e-testing"
       source "${BASE_DIR}/.env"

       "${BASE_DIR}/.ci/scripts/install-test-dependencies.sh" "${SUITE}"

       REPORT="${BASE_DIR}/outputs/TEST-$(uname -m)-${SUITE}"

       FORMAT=junit:${REPORT}.xml make --no-print-directory -C "${BASE_DIR}/e2e/_suites/${SUITE}" functional-test
