---
- name: Extend environment
  lineinfile:
    state: present
    line: "{{item}}"
    insertafter: EOF
    dest: "/home/{{ansible_user}}/e2e-testing/.env"
    create: yes
  with_items:
    - "SUITE={{ lookup('env', 'SUITE') or 'fleet' }}"
    - "STACK_VERSION={{ lookup('env', 'STACK_VERSION') or '8.0.0-SNAPSHOT' }}"
    - "BEAT_VERSION={{ lookup('env', 'BEAT_VERSION') or '8.0.0-SNAPSHOT' }}"
    - "ELASTIC_APM_GLOBAL_LABELS={{ lookup('env', 'ELASTIC_APM_GLOBAL_LABELS') }}"

- name: Create test script file
  become: no
  copy:
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: '0777'
    dest: "/home/{{ansible_user}}/e2e-testing/.ci/scripts/functional-test.sh"
    content: |
       #!/usr/bin/env bash

       ## Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
       ## or more contributor license agreements. Licensed under the Elastic License;
       ## you may not use this file except in compliance with the Elastic License.

       set -euxo pipefail

       BASE_DIR="/home/{{ansible_user}}/e2e-testing"
       source "${BASE_DIR}/.env"

       "${BASE_DIR}/.ci/scripts/install-test-dependencies.sh" "${SUITE}"

       SEED=$(date +%Y-%m-%d-%H:%M:%S)
       REPORT="${BASE_DIR}/outputs/TEST-$(uname -m)-${SUITE}-{{runId}}-${SEED}"
       ELASTIC_APM_SECRET_TOKEN={{ lookup('env', 'ELASTIC_APM_SECRET_TOKEN') }}
       ELASTIC_APM_SERVER_URL={{ lookup('env', 'ELASTIC_APM_SERVER_URL') }}
       OTEL_EXPORTER_OTLP_ENDPOINT={{ lookup('env', 'OTEL_EXPORTER_OTLP_ENDPOINT') }}
       OTEL_EXPORTER_OTLP_HEADERS={{ lookup('env', 'OTEL_EXPORTER_OTLP_HEADERS') }}

       ELASTIC_APM_SECRET_TOKEN=

       TAGS="${1}" \
         FORMAT=junit:${REPORT}.xml \
         STACK_VERSION=${STACK_VERSION} \
         BEAT_VERSION=${BEAT_VERSION} \
         # ELASTIC_APM_SECRET_TOKEN=${ELASTIC_APM_SECRET_TOKEN} \
         # ELASTIC_APM_SERVER_URL=${ELASTIC_APM_SERVER_URL} \
         # OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT} \
         # OTEL_EXPORTER_OTLP_HEADERS=${OTEL_EXPORTER_OTLP_HEADERS} \
         make --no-print-directory -C "${BASE_DIR}/e2e/_suites/${SUITE}" functional-test
