---
  - "automation":
    - ".ci/**/*.*"
    - ".github/**/*.*"
    - "notice/**/*.*"
    - "**/Makefile"
    - ".pre-commit-config.yaml"
  - "cli":
    - "cli/**/*.*"
<<<<<<< HEAD
  - "helm":
    - "e2e/_suites/helm/**/*.*"
  - "Team: Ingest Management":
=======
  - "Team: Agent":
>>>>>>> d5541388 (fix: remove Helm Chart tests (#3285))
    - "e2e/_suites/fleet/**/*.*"
  - "licenses":
    - "notice/**/*.*"
    - "**/go.mod"
    - "**/go.sum"
    - "**/LICENSE.txt"
    - "**/NOTICE.txt"
  - "metricbeat":
    - "e2e/_suites/metricbeat/**/*.*"
