---
  - "automation":
    - ".ci/**/*.*"
    - ".github/**/*.*"
    - "notice/**/*.*"
    - "**/Makefile"
    - ".pre-commit-config.yaml"
  - "cli":
    - "cli/**/*.*"
  - "helm":
    - "e2e/_suites/helm/**/*.*"
  - "Team: Agent":
    - "e2e/_suites/fleet/**/*.*"
  - "licenses":
    - "notice/**/*.*"
    - "**/go.mod"
    - "**/go.sum"
    - "**/LICENSE.txt"
    - "**/NOTICE.txt"
