queue_rules:
  - name: default
    conditions:
      - check-success=beats-ci/e2e-testing/pr-merge

pull_request_rules:
  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
        comment:
          message: |
            This pull request is now in conflict. Could you fix it @{{author}}? 🙏
            To fixup this pull request, you can check out it locally. See documentation: https://help.github.com/articles/checking-out-pull-requests-locally/
            ```
            git fetch upstream
            git checkout -b {{head}} upstream/{{head}}
            git merge upstream/{{base}}
            git push upstream {{head}}
            ```
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch:
  - name: automatic squash and merge with success checks for those automated PRs created by the apmmachine.
    conditions:
      - -merged
      - -closed
      - label=automation
      - author=apmmachine
      - head~=^updatecli.*
    actions:
      queue:
        method: squash
        name: default
  - name: delete upstream branch after merging changes the automated PR or it's closed
    conditions:
      - or:
        - merged
        - closed
      - and:
        - label=automation
        - head~=^updatecli.*
    actions:
      delete_head_branch:
  - name: remove-backport label
    conditions:
      - label~=backport-v
    actions:
      label:
        remove:
          - backport-skip
  - name: notify the backport policy
    conditions:
      - -label~=^backport
      - base=main
    actions:
      comment:
        message: |
          This pull request does not have a backport label. Could you fix it @{{author}}? 🙏
          To fixup this pull request, you need to add the backport labels for the needed
          branches, such as:
          * `backport-v./d./d./d` is the label to automatically backport to the `7./d` branch. `/d` is the digit
          **NOTE**: `backport-skip` has been added to this pull request.
      label:
        add:
          - backport-skip
  - name: notify the backport has not been merged yet
    conditions:
      - -merged
      - -closed
      - author=mergify[bot]
      - "#check-success>0"
      - schedule=Mon-Mon 06:00-10:00[Europe/Paris]
      - created-at<2 days ago
    actions:
      comment:
        message: |
          This pull request has not been merged yet. Could you please review and merge it @{{ assignee | join(', @') }}? 🙏
  - name: automatic close the automated PRs that have not been merged.
    conditions:
      - -merged
      - -closed
      - author=apmmachine
      - schedule=Mon-Fri 06:00-10:00[Europe/Paris]
      - created-at<3 days ago
      - head~=^updatecli.*
    actions:
      close:
        message: |
          This pull request has been automatically closed by Mergify.
          There are likely new up-to-date and open pull requests.
  - name: backport patches to 7.17 branch
    conditions:
      - merged
      - base=main
      - label=backport-v7.17.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "7.17"
        title: "[{{ destination_branch }}](backport #{{ number }}) {{ title }}"
  - name: backport patches to 8.3 branch
    conditions:
      - merged
      - base=main
      - label=backport-v8.3.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.3"
        title: "[{{ destination_branch }}](backport #{{ number }}) {{ title }}"
  - name: backport patches to 8.4 branch
    conditions:
      - merged
      - label=backport-v8.4.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.4"
        labels:
          - "backport"
        title: "[{{ destination_branch }}](backport #{{ number }}) {{ title }}"
  - name: backport patches to 8.5 branch
    conditions:
      - merged
      - label=backport-v8.5.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.5"
        labels:
          - "backport"
        title: "[{{ destination_branch }}](backport #{{ number }}) {{ title }}"
  - name: backport patches to 8.6 branch
    conditions:
      - merged
      - label=backport-v8.6.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.6"
        labels:
          - "backport"
        title: "[{{ destination_branch }}](backport #{{ number }}) {{ title }}"
  - name: backport patches to 8.7 branch
    conditions:
      - merged
      - label=backport-v8.7.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.7"
        labels:
          - "backport"
        title: "[{{ destination_branch }}](backport #{{ number }}) {{ title }}"
  - name: backport patches to 8.8 branch
    conditions:
      - merged
      - label=backport-v8.8.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.8"
        labels:
          - "backport"
        title: "[{{ destination_branch }}](backport #{{ number }}) {{ title }}"
  - name: backport patches to 8.9 branch
    conditions:
      - merged
      - label=backport-v8.9.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.9"
        labels:
          - "backport"
        title: "[{{ destination_branch }}](backport #{{ number }}) {{ title }}"
  - name: backport patches to 8.10 branch
    conditions:
      - merged
      - label=backport-v8.10.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.10"
        labels:
          - "backport"
        title: "[{{ destination_branch }}](backport #{{ number }}) {{ title }}"
