apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-server
  labels:
    app: fleet-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleet-server
  template:
    metadata:
      labels:
        app: fleet-server
    spec:
      containers:
      - name: fleet-server
        image: docker.elastic.co/beats/elastic-agent:8.6.2-7c4539d9-SNAPSHOT
        env:
        - name: FLEET_SERVER_ENABLE
          value: "1"
        - name: FLEET_SERVER_INSECURE_HTTP
          value: "1"
        - name: KIBANA_FLEET_SETUP
          value: "1"
        - name: KIBANA_FLEET_HOST
          value: "http://kibana:5601"
        - name: FLEET_SERVER_HOST
          value: "0.0.0.0"
        - name: FLEET_SERVER_PORT
          value: "8220"
