apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-server
  labels:
    app: fleet-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleet-server
  template:
    metadata:
      labels:
        app: fleet-server
    spec:
      containers:
      - name: fleet-server
<<<<<<< HEAD
        image: docker.elastic.co/beats/elastic-agent:8.4.4-dcd4a95f-SNAPSHOT
=======
        image: docker.elastic.co/beats/elastic-agent:8.7.0-04d5f080-SNAPSHOT
>>>>>>> d5541388 (fix: remove Helm Chart tests (#3285))
        env:
        - name: FLEET_SERVER_ENABLE
          value: "1"
        - name: FLEET_SERVER_INSECURE_HTTP
          value: "1"
        - name: KIBANA_FLEET_SETUP
          value: "1"
        - name: KIBANA_FLEET_HOST
          value: "http://kibana:5601"
        - name: FLEET_SERVER_HOST
          value: "0.0.0.0"
        - name: FLEET_SERVER_PORT
          value: "8220"
