---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fleet-server-role
  namespace: default
  labels:
    app: fleet-server
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs: ["get", "create", "update", "list", "watch", "update", "patch", "delete"]
