---
PLATFORMS:
  stack:
    image: "ami-0d90bed76900e679a"
    instance_type: "c5.4xlarge"
    username: admin
  helm:
    image: "ami-0d90bed76900e679a"
    instance_type: "c5.2xlarge"
    username: admin
  debian_arm64:
    image: "ami-06dac44ad759182bd"
    instance_type: "a1.large"
    username: admin
  debian_amd64:
    image: "ami-0d90bed76900e679a"
    instance_type: "c5.4xlarge"
    username: admin
  sles15:
    image: "ami-0f7cb53c916a75006"
    instance_type: "c5.4xlarge"
    username: ec2-user
  fleet_elastic_pkg:
    image: "ami-0d90bed76900e679a"
    instance_type: "c5.4xlarge"
    username: admin
  kubernetes_autodiscover:
    image: "ami-0d90bed76900e679a"
    instance_type: "c5.4xlarge"
    username: admin

SUITES:
  - suite: "fleet"
    scenarios:
      - name: "Fleet"
        tags: "fleet_mode_agent"
        platforms: ["debian_arm64", "debian_amd64", "sles15"]
      - name: "Integrations"
        tags: "integrations"
        platforms: ["debian_arm64", "debian_amd64"]
      - name: "APM Integration"
        tags: "apm_server"
        platforms: ["fleet_elastic_pkg"]
      - name: "Linux Integration"
        tags: "linux_integration"
        platforms: ["debian_arm64", "debian_amd64"]
      # - name: "Permissions Output change"
      #   tags: "permission_change"
      #   platforms: ["debian_arm64", "debian_amd64"]
      # - name: "System Integration"
      #   tags: "system_integration"
      #   platforms: ["debian_arm64", "debian_amd64"]
      # - name: "Stand-alone"
      #   tags: "stand_alone_agent"
      #   platforms: ["fleet_elastic_pkg"]
      - name: "Backend Processes"
        tags: "backend_processes"
        platforms: ["debian_arm64", "debian_amd64"]
      - name: "Beats Background Processes"
        tags: "running_on_beats"
        platforms: ["debian_arm64", "debian_amd64"]
