---
SUITES:
  - suite: "helm"
    platforms:
      - labels: "ubuntu-18.04"
    scenarios:
      - name: "APM Server"
        tags: "apm-server"
      - name: "Filebeat"
        tags: "filebeat"
      - name: "Metricbeat"
        tags: "metricbeat"
  - suite: "fleet"
    platforms:
      - labels: "arm64"
      - labels: "ubuntu-18.04"
        provider: "elastic-package"
    scenarios:
      - name: "Fleet"
        pullRequestFilter: " && ~debian"
        tags: "fleet_mode_agent"
        platforms:
          - labels: "ubuntu-18.04"
            provider: "elastic-package"
          - labels: "windows-2019"
            provider: "elastic-package"
      - name: "Integrations"
        pullRequestFilter: " && ~debian"
        tags: "integrations"
      - name: "APM Integration"
        pullRequestFilter: " && ~debian"
        tags: "apm_server"
      - name: "Linux Integration"
        pullRequestFilter: " && ~debian"
        tags: "linux_integration"
      - name: "Policies"
        pullRequestFilter: " && ~debian"
        tags: "policies"
      - name: "System Integration"
        platforms:
          - labels: "ubuntu-18.04"
            provider: "elastic-package"
        pullRequestFilter: " && ~debian"
        tags: "system_integration"
      - name: "Stand-alone"
        platforms:
          - labels: "ubuntu-18.04"
            provider: "elastic-package"
        pullRequestFilter: " && ~ubi8"
        tags: "stand_alone_agent"
      - name: "Backend Processes"
        pullRequestFilter: " && ~debian"
        tags: "backend_processes"
      - name: "Beats Background Processes"
        pullRequestFilter: " && ~debian"
        tags: "running_on_beats"
  - suite: "kubernetes-autodiscover"
    platforms:
      - labels: "ubuntu-18.04"
    scenarios:
      - name: "kubernetes autodiscover with elastic-agent"
        tags: "kubernetes-autodiscover && elastic-agent"
      - name: "kubernetes autodiscover with filebeat"
        tags: "kubernetes-autodiscover && filebeat"
      - name: "kubernetes autodiscover with heartbeat"
        tags: "kubernetes-autodiscover && heartbeat"
      - name: "kubernetes autodiscover with metricbeat"
        tags: "kubernetes-autodiscover && metricbeat"
