---
SUITES:
#  - suite: "helm"
#    provider: "docker"
#    scenarios:
#      - name: "APM Server"
#        tags: "apm-server"
#        platforms: [ "debian_10_amd64_preinstalled" ]
#      - name: "Filebeat"
#        tags: "filebeat"
#        platforms: [ "debian_10_amd64_preinstalled" ]
#      - name: "Metricbeat"
#        tags: "metricbeat"
#        platforms: [ "debian_10_amd64_preinstalled" ]
  - suite: "fleet"
    scenarios:
      - name: "Fleet"
        tags: "fleet_mode"
        platforms: ["centos8_amd64_preinstalled"]
