---
SUITES:
  - suite: "helm"
    feature: "apm-server"
  - suite: "helm"
    feature: "filebeat"
  - suite: "helm"
    feature: "metricbeat"
  - suite: "ingest-manager"
    feature: "agent_endpoint_integration"
  - suite: "ingest-manager"
    feature: "stand_alone_mode"
  - suite: "ingest-manager"
    feature: "fleet_mode"
  - suite: "metricbeat"
    feature: "apache"
  - suite: "metricbeat"
    feature: "metricbeat"
  - suite: "metricbeat"
    feature: "mysql"
  - suite: "metricbeat"
    feature: "redis"
  - suite: "metricbeat"
    feature: "vsphere"
