---
SUITES:
  - suite: "helm"
    tags: "apm-server"
  - suite: "helm"
    tags: "filebeat"
  - suite: "helm"
    tags: "metricbeat"
  - suite: "metricbeat"
    tags: "integrations && activemq"
  - suite: "metricbeat"
    tags: "integrations && apache"
  - suite: "metricbeat"
    tags: "integrations && ceph"
  - suite: "metricbeat"
    tags: "integrations && dropwizard"
  - suite: "metricbeat"
    tags: "integrations && envoyproxy"
  - suite: "metricbeat"
    tags: "integrations && etcd"
  - suite: "metricbeat"
    tags: "integrations && haproxy"
  - suite: "metricbeat"
    tags: "integrations && kafka"
  - suite: "metricbeat"
    tags: "metricbeat"
  - suite: "metricbeat"
    tags: "integrations && mysql"
  - suite: "metricbeat"
    tags: "integrations && oracle"
  - suite: "metricbeat"
    tags: "integrations && redis"
  - suite: "metricbeat"
    tags: "integrations && redisenterprise"
  - suite: "metricbeat"
    tags: "integrations && vsphere"
