---
SUITES:
  - suite: "fleet"
    scenarios:
      - name: "Fleet"
        tags: "fleet_mode_agent"
        platforms: ["centos8_arm64", "centos8_amd64", "debian_10_arm64", "debian_10_amd64", "sles15"]
      - name: "Integrations"
        tags: "integrations"
        platforms: ["debian_10_amd64"]
      - name: "APM Integration"
        tags: "apm_server"
        platforms: ["debian_10_amd64"]
      - name: "Linux Integration"
        tags: "linux_integration"
        platforms: ["debian_10_arm64", "debian_10_amd64", "sles15"]
      - name: "Permissions Output change"
        tags: "permission_change"
        platforms: ["debian_10_arm64", "debian_10_amd64", "sles15"]
      - name: "Backend Processes"
        tags: "backend_processes"
        platforms: ["debian_10_arm64", "debian_10_amd64", "sles15"]
      - name: "Beats Background Processes"
        tags: "running_on_beats"
        platforms: ["debian_10_arm64", "debian_10_amd64", "sles15"]
  - suite: "kubernetes-autodiscover"
    provider: "docker"
    scenarios:
      - name: "kubernetes autodiscover with filebeat"
        tags: "filebeat"
        platforms: ["debian_10_amd64"]
      - name: "kubernetes autodiscover with heartbeat"
        tags: "heartbeat"
        platforms: ["debian_10_amd64"]
      - name: "kubernetes autodiscover with metricbeat"
        tags: "metricbeat"
        platforms: ["debian_10_amd64"]
