---
SUITES:
  - suite: "helm"
    platforms:
      - "ubuntu-18.04"
    scenarios:
      - name: "APM Server"
        tags: "apm-server"
      - "Filebeat":
        tags: "filebeat"
      - "Metricbeat":
        tags: "metricbeat"
  - suite: "fleet"
    platforms:
      - "ubuntu-18.04"
    scenarios:
      - name: "Fleet"
        tags: "fleet_mode_agent"
      - name: "Endpoint Integration"
        tags: "agent_endpoint_integration"
      - name: "Stand-alone"
        tags: "stand_alone_agent"
  - suite: "metricbeat"
    platforms:
      - "ubuntu-18.04"
    scenarios:
      - name: "ActiveMQ"
        tags: "integrations && activeMQ"
      - name: "Apache"
        tags: "integrations && apache"
      - name: "Ceph"
        tags: "integrations && ceph"
      - name: "Dropwizard"
        tags: "integrations && dropwizard"
      - name: "Envoy Proxy"
        tags: "integrations && envoyproxy"
      - name: "etcd"
        tags: "integrations && etcd"
      - name: "HAProxy"
        tags: "integrations && haproxy"
      - name: "Kafka"
        tags: "integrations && kafka"
      - name: "Metricbeat"
        tags: "metricbeat"
      - name: "MySQL"
        tags: "integrations && mysql"
      - name: "Oracle"
        tags: "integrations && oracle"
      - name: "Redis"
        tags: "integrations && redis"
      - name: "Redis Enterprise"
        tags: "integrations && redisenterprise"
      - name: "vSphere"
        tags: "integrations && vsphere"
