---
SUITES:
  - suite: "fleet"
    scenarios:
      - name: "Fleet"
        tags: "fleet_mode"
        platforms: ["centos8_arm64", "centos8_amd64", "debian_arm64", "debian_amd64", "sles15"]
      - name: "Integrations"
        tags: "integrations"
        platforms: ["debian_arm64", "debian_amd64", "sles15"]
      - name: "APM Integration"
        tags: "apm_server"
        platforms: ["debian_amd64"]
      - name: "Linux Integration"
        tags: "linux_integration"
        platforms: ["debian_arm64", "debian_amd64", "sles15"]
      # - name: "Permissions Output change"
      #   tags: "permission_change"
      #   platforms: ["debian_arm64", "debian_amd64", "sles15"]
      - name: "System Integration"
        tags: "system_integration"
        platforms: ["debian_arm64", "debian_amd64", "sles15"]
      # - name: "Stand-alone"
      #   tags: "stand_alone_mode"
      #   platforms: ["fleet_elastic_pkg"]
      - name: "Backend Processes"
        tags: "backend_processes"
        platforms: ["debian_arm64", "debian_amd64", "sles15"]
      - name: "Beats Background Processes"
        tags: "running_on_beats"
        platforms: ["debian_arm64", "debian_amd64", "sles15"]
      - name: "Upgrade Agent"
        tags: "upgrade_agent"
        platforms: ["debian_arm64", "debian_amd64", "sles15"]
