---
SUITES:
  - suite: "helm"
    provider: "docker"
    scenarios:
      - name: "Filebeat"
        tags: "filebeat"
        platforms: ["debian_10_amd64"]
      - name: "Metricbeat"
        tags: "metricbeat"
        platforms: ["debian_10_amd64"]
  - suite: "kubernetes-autodiscover"
    provider: "docker"
    scenarios:
      - name: "kubernetes autodiscover with filebeat"
        tags: "filebeat"
        platforms: ["debian_10_amd64"]
      - name: "kubernetes autodiscover with heartbeat"
        tags: "heartbeat"
        platforms: ["debian_10_amd64"]
      - name: "kubernetes autodiscover with metricbeat"
        tags: "metricbeat"
        platforms: ["debian_10_amd64"]
