---
SUITES:
  - suite: "helm"
    platforms:
      - "ubuntu-18.04"
    scenarios:
      - name: "APM Server"
        tags: "apm-server"
      - name: "Filebeat"
        tags: "filebeat"
      - name: "Metricbeat"
        tags: "metricbeat"
  - suite: "fleet"
    platforms:
      - "arm64"
      - "ubuntu-18.04"
    scenarios:
      - name: "Fleet"
        pullRequestFilter: " && ~debian"
        tags: "fleet_mode_agent"
      - name: "Endpoint Integration"
        platforms:
          - "ubuntu-18.04"
        pullRequestFilter: " && ~debian"
        tags: "agent_endpoint_integration"
      - name: "Linux Integration"
        pullRequestFilter: " && ~debian"
        tags: "linux_integration"
      - name: "System Integration"
        platforms:
          - "ubuntu-18.04"
        pullRequestFilter: " && ~debian"
        tags: "system_integration"
      - name: "Stand-alone"
        pullRequestFilter: " && ~ubi8"
        tags: "stand_alone_agent"
      - name: "Backend Processes"
        pullRequestFilter: " && ~debian"
        tags: "backend_processes"
      - name: "Beats Background Processes"
        pullRequestFilter: " && ~debian"
        tags: "running_on_beats"
  - suite: "metricbeat"
    platforms:
      - "ubuntu-18.04"
    scenarios:
      - name: "ActiveMQ"
        tags: "integrations && activeMQ"
      - name: "Apache"
        tags: "integrations && apache"
      - name: "Ceph"
        tags: "integrations && ceph"
      - name: "Dropwizard"
        tags: "integrations && dropwizard"
      - name: "Envoy Proxy"
        tags: "integrations && envoyproxy"
      - name: "etcd"
        tags: "integrations && etcd"
      - name: "HAProxy"
        tags: "integrations && haproxy"
      - name: "Kafka"
        tags: "integrations && kafka"
      - name: "Metricbeat"
        tags: "metricbeat"
      - name: "MS SQL Server"
        tags: "integrations && mssql"
      - name: "MySQL"
        pullRequestFilter: " && ~old_versions"
        tags: "integrations && mysql"
      - name: "Oracle"
        tags: "integrations && oracle"
      - name: "Redis"
        tags: "integrations && redis"
      - name: "Redis Enterprise"
        tags: "integrations && redisenterprise"
      - name: "vSphere"
        tags: "integrations && vsphere"
  - suite: "kubernetes-autodiscover"
    platforms:
      - "ubuntu-18.04"
    scenarios:
      - name: "kubernetes autodiscover with filebeat"
        tags: "kubernetes-autodiscover && filebeat"
      - name: "kubernetes autodiscover with heartbeat"
        tags: "kubernetes-autodiscover && heartbeat"
      - name: "kubernetes autodiscover with metricbeat"
        tags: "kubernetes-autodiscover && metricbeat"
