---
PLATFORMS:
  stack:
    description: "Debian 10 AMD64, used specifically for running the stack"
    image: "ami-0d90bed76900e679a"
    instance_type: "t3.xlarge"
    username: admin
  centos8_arm64:
    description: "CentOS Stream 8 aarch64"
    image: "ami-01cdc9e8306344fe0"
    instance_type: "a1.large"
    username: centos
  centos8_amd64:
    description: "CentOS Stream 8 x86_64"
    image: "ami-045b0a05944af45c1"
    instance_type: "t3.xlarge"
    username: centos
  debian_arm64:
    description: "Debian 10 ARM64"
    image: "ami-06dac44ad759182bd"
    instance_type: "a1.large"
    username: admin
  debian_amd64:
    description: "Debian 10 AMD64"
    image: "ami-0d90bed76900e679a"
    instance_type: "t3.xlarge"
    username: admin
  oracle_linux8:
    description: "Oracle Linux 8 update 3 for x86_64 HVM"
    image: "ami-00371eeb8fd8e0e16"
    instance_type: "t3.xlarge"
    username: ec2-user
  sles15:
    description: "SUSE Linux Enterprise Server 15 SP3 (HVM), SSD Volume Type -  64bit ARM"
    image: "ami-0f7cb53c916a75006"
    instance_type: "t3.xlarge"
    username: ec2-user
  fleet_elastic_pkg:
    description: "Debian 10 AMD64"
    image: "ami-0d90bed76900e679a"
    instance_type: "t3.xlarge"
    username: admin
 debian_11_amd64:
    description: "Debian 11 AMD64"
    image: "ami-0c6acff4e66eba1f1"
    instance_type: "t3.xlarge"
    username: admin
 ubuntu_22.04:
    description: "Ubuntu 22.04"
    image: "ami-0672b5f41af818f25"
    instance_type: "t3.xlarge"
    username: admin