---
PLATFORMS:
  stack:
    description: "Debian 10 AMD64, used specifically for running the stack"
    image: "ami-0d90bed76900e679a"
    instance_type: "t3.xlarge"
    shell_type: sh
    username: admin
  centos8_arm64:
    description: "CentOS Stream 8 aarch64"
    image: "ami-01cdc9e8306344fe0"
    instance_type: "a1.large"
    shell_type: sh
    username: centos
  centos8_amd64:
    description: "CentOS Stream 8 x86_64"
    image: "ami-045b0a05944af45c1"
    instance_type: "t3.xlarge"
    shell_type: sh
    username: centos
  debian_10_arm64:
    description: "Debian 10 ARM64"
    image: "ami-06dac44ad759182bd"
    instance_type: "a1.large"
    shell_type: sh
    username: admin
  debian_10_amd64:
    description: "Debian 10 AMD64"
    image: "ami-0d90bed76900e679a"
    instance_type: "t3.xlarge"
    shell_type: sh
    username: admin
  debian_11_amd64:
    description: "Debian 11 AMD64"
    image: "ami-0c7c4e3c6b4941f0f"
    instance_type: "t3.xlarge"
    shell_type: sh
    username: admin
  oracle_linux8:
    description: "Oracle Linux 8 update 3 for x86_64 HVM"
    image: "ami-00371eeb8fd8e0e16"
    instance_type: "t3.xlarge"
    shell_type: sh
    username: ec2-user
  sles15:
    description: "SUSE Linux Enterprise Server 15 SP3 (HVM), SSD Volume Type -  64bit ARM"
    image: "ami-0f7cb53c916a75006"
    instance_type: "t3.xlarge"
    shell_type: sh
    username: ec2-user
  windows2019:
    description: "Windows 2019 x86_64 (HVM)"
    image: "ami-0587bd602f1da2f1d"
    instance_type: "c5.2xlarge"
    shell_type: cmd
    username: ogc
  fleet_elastic_pkg:
    description: "Debian 10 AMD64"
    image: "ami-038f1e4512905b02e"
    instance_type: "t3.xlarge"
    shell_type: sh
    username: admin
  ubuntu_22_04_amd64:
    description: "Ubuntu 22.04 AMD64"
    image: "ami-0aeb7c931a5a61206"
    instance_type: "t3.xlarge"
    shell_type: sh
    username: ubuntu
  ubuntu_22_04_amd64_preinstalled:
    description: "Ubuntu 22.04 AMD64 Preinstalled"
    image: "ubuntu-2204-e2e-runner-1"
    instance_type: "t3.xlarge"
    shell_type: sh
    username: ubuntu
    dependencies_installed: true
