---
SUITES:
  - suite: "helm"
    tags: "apm-server"
  - suite: "helm"
    tags: "filebeat"
  - suite: "helm"
    tags: "metricbeat"
  - suite: "fleet"
    tags: "agent_endpoint_integration"
  - suite: "fleet"
    tags: "stand_alone_agent"
  - suite: "fleet"
    tags: "fleet_mode_agent"
  - suite: "metricbeat"
    tags: "apache"
  - suite: "metricbeat"
    tags: "metricbeat"
  - suite: "metricbeat"
    tags: "mysql"
  - suite: "metricbeat"
    tags: "redis"
  - suite: "metricbeat"
    tags: "vsphere"
