version: '2.4'
services:
  elasticsearch:
    healthcheck:
      test: ["CMD", "curl", "-f", "-u", "elastic:changeme", "http://127.0.0.1:9200/"]
      retries: 300
      interval: 1s
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - network.host=
      - transport.host=127.0.0.1
      - http.host=0.0.0.0
      - indices.id_field_data.enabled=true
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - xpack.security.authc.token.enabled=true
      - xpack.security.authc.token.timeout=60m
      - ELASTIC_USERNAME=admin
      - ELASTIC_PASSWORD=changeme
    image: "docker.elastic.co/elasticsearch/elasticsearch:${stackVersion:-7.17.18-b8c750dd-SNAPSHOT}"
    platform: ${stackPlatform:-linux/amd64}
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch-roles.yml:/usr/share/elasticsearch/config/roles.yml
      - ./elasticsearch-users:/usr/share/elasticsearch/config/users
      - ./elasticsearch-users_roles:/usr/share/elasticsearch/config/users_roles
  kibana:
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: "curl -f http://localhost:5601/login | grep kbn-injected-metadata 2>&1 >/dev/null"
      retries: 600
      interval: 1s
    image: "docker.elastic.co/${kibanaDockerNamespace:-kibana}/kibana:${kibanaVersion:-7.17.18-b8c750dd-SNAPSHOT}"
    platform: ${stackPlatform:-linux/amd64}
    ports:
      - "5601:5601"
    volumes:
      - ./${kibanaProfile:-default}/kibana.config.yml:/usr/share/kibana/config/kibana.yml
