version: '2.4'
services:
  elasticsearch:
    healthcheck:
      interval: 10s
      retries: 100
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=500ms"]
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - network.host="0.0.0.0"
      - transport.host=127.0.0.1
      - http.host=0.0.0.0
      - indices.id_field_data.enabled=true
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - xpack.security.authc.token.enabled=true
      - xpack.security.authc.token.timeout=60m
      - ELASTIC_USERNAME=admin
      - ELASTIC_PASSWORD=changeme
<<<<<<< HEAD
    image: "docker.elastic.co/elasticsearch/elasticsearch:${stackVersion:-8.4.4-dcd4a95f-SNAPSHOT}"
=======
    image: "docker.elastic.co/elasticsearch/elasticsearch:${stackVersion:-8.7.0-04d5f080-SNAPSHOT}"
>>>>>>> d5541388 (fix: remove Helm Chart tests (#3285))
    platform: ${stackPlatform:-linux/amd64}
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch-roles.yml:/usr/share/elasticsearch/config/roles.yml
      - ./elasticsearch-users:/usr/share/elasticsearch/config/users
      - ./elasticsearch-users_roles:/usr/share/elasticsearch/config/users_roles
  kibana:
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
<<<<<<< HEAD
      test: "curl -f http://localhost:5601/login | grep kbn-injected-metadata 2>&1 >/dev/null"
      retries: 600
      interval: 1s
    image: "docker.elastic.co/${kibanaDockerNamespace:-kibana}/kibana:${kibanaVersion:-8.4.4-dcd4a95f-SNAPSHOT}"
=======
      test: ["CMD-SHELL", "curl -u admin:changeme -s http://localhost:5601/api/status | grep -q 'All services are available'"]
      retries: 60
      interval: 10s
    image: "docker.elastic.co/${kibanaDockerNamespace:-kibana}/kibana:${kibanaVersion:-8.7.0-04d5f080-SNAPSHOT}"
>>>>>>> d5541388 (fix: remove Helm Chart tests (#3285))
    platform: ${stackPlatform:-linux/amd64}
    ports:
      - "5601:5601"
    volumes:
      - ./${kibanaProfile:-default}/kibana.config.yml:/usr/share/kibana/config/kibana.yml
