apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
<<<<<<< HEAD
        image: docker.elastic.co/elasticsearch/elasticsearch:8.4.4-dcd4a95f-SNAPSHOT
=======
        image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0-04d5f080-SNAPSHOT
>>>>>>> d5541388 (fix: remove Helm Chart tests (#3285))
        envFrom:
          - configMapRef:
              name: elasticsearch-config
        ports:
        - containerPort: 9200
          name: client
