apiVersion: apps/v1
kind: Deployment
metadata:
  name: package-registry
  labels:
    app: package-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: package-registry
  template:
    metadata:
      labels:
        app: package-registry
    spec:
      containers:
      - name: package-registry
        image: docker.elastic.co/package-registry/distribution:production
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
