version: '2.3'
services:
  kibana:
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=changeme
    image: "docker.elastic.co/kibana/kibana:${kibanaTag}"
    ports:
      - "5601:5601"
