version: '2.3'
services:
  filebeat:
    environment:
      - BEAT_STRICT_PERMS=${beatStricPerms:-false}
      - logLevel=${logLevel:-info}
      - monitoringEsHost=${monitoringEsHost:-elasticsearch}
      - monitoringEsPort=${monitoringEsPort:-9200}
      - xpackMonitoring=${xpackMonitoring:-true}
    image: "docker.elastic.co/beats/filebeat:${filebeatTag}"
    labels:
      co.elastic.logs/module: "${serviceName}"
    volumes:
      - "${filebeatConfigFile}:/usr/share/filebeat/filebeat.yml"
