---
- name: "Delete instance {{ item }}"
  gcp_compute_instance:
      state: absent
      name: "{{item}}"
      zone: "{{ zone }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
        - https://www.googleapis.com/auth/compute
  register: instance
