apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana
data:
  kibana.yml: |-
    ---
    server.name: kibana
    server.host: "0.0.0.0"

    elasticsearch.hosts: [ "http://elasticsearch:9200" ]
    elasticsearch.username: elastic
    elasticsearch.password: changeme
    monitoring.ui.container.elasticsearch.enabled: true

    xpack.encryptedSavedObjects.encryptionKey: "12345678901234567890123456789012"

    xpack.fleet.enabled: true
    xpack.fleet.registryUrl: http://package-registry:8080
    xpack.fleet.agents.enabled: true
    xpack.fleet.agents.elasticsearch.host: http://elasticsearch:9200
    xpack.fleet.agents.fleet_server.hosts: ["http://fleet-server:8220"]
    xpack.fleet.agents.kibana.host: "http://kibana:5601"
    xpack.fleet.agents.tlsCheckDisabled: true
