name: golangci-lint
on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    name: lint
    runs-on: ${{  matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: .go-version
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          version: v1.51.2
          args: --timeout=30m --whole-files
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
