name: golangci-lint
on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    name: lint
    runs-on: ${{  matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Fetch Go version from .go-version
        run: echo "GO_VERSION=$(cat .go-version)" >> $GITHUB_ENV
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          version: v1.51.2
          args: --timeout=30m --whole-files
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
