name: golangci-lint
on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    name: lint
    runs-on: ${{  matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: .go-version
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6.0.1
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.59.1
          # Optional: golangci-lint command line arguments.
          args: --timeout=30m
          # Optional: if set to true then the all caching functionality will be complete disabled,
          #           takes precedence over all other caching options.
          skip-cache: true
