name: k8s-autodiscovery-test

on:
  schedule:
    - cron: '0 18 * * *'
  pull_request:
    branches:
      - main
    paths:
      - .stack-version
      - 'e2e/_suites/kubernetes-autodiscover/**'
      - .github/workflows/k8s-autodiscovery-test.yml
  push:
    branches:
      - main
    paths:
      - .stack-version
      - 'e2e/_suites/kubernetes-autodiscover/**'
      - .github/workflows/k8s-autodiscovery-test.yml

permissions:
  contents: read

# Cancel previous runs only on pull requests
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ !!github.head_ref }}

jobs:
  k8s-autodiscovery-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: get-go-version
        name: Get Go version
        run: echo "version=$(cat .go-version)" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.get-go-version.outputs.version }}
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.8.0
      - name: Run k8s autodiscovery test
        working-directory: e2e/_suites/kubernetes-autodiscover
        env:
          OP_LOG_LEVEL: DEBUG
        run: go test -timeout 90m -v
