---
name: pre-commit

on:
  push:
    branches:
      - 'main'
      - '8**'
      - '7.17'
  pull_request:

# limit the access of the generated GITHUB_TOKEN
permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version-file: .go-version
    - uses: actions/setup-python@v3
    - name: Install dependencies
      run: .ci/scripts/install-dependencies.sh
    - uses: elastic/apm-pipeline-library/.github/actions/pre-commit@current
