---
## Workflow to lint and test
name: pull-request

permissions:
  contents: read

on:
  pull_request:
  push:

jobs:
  test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: .go-version
          cache: true
          cache-dependency-path: go.sum
      - name: build
        run: .ci/scripts/build-test.sh
      - uses: actions/upload-artifact@v3  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: test-results
          path: outputs/TEST-unit-*.xml
