---
## Workflow to lint and test
name: pull-request

permissions:
  contents: read

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      JENKINS_URL: https://apm-ci.elastic.co/
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0

  test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch Go version from .go-version
        run: echo "GO_VERSION=$(cat .go-version)" >> $GITHUB_ENV
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: go.sum
      - name: build
        run: .ci/scripts/build-test.sh
      - uses: actions/upload-artifact@v3  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: test-results
          path: outputs/TEST-unit-*.xml

  docs:
    name: Run docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: elastic/apm-pipeline-library/.github/actions/docker-login@gh_actions
        with:
          registry: docker.elastic.co
          secret: secret/observability-team/ci/docker-registry/prod
          url: ${{ secrets.VAULT_ADDR }}
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
      - name: build
        run: make -C e2e build-docs
